apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../base
patches:
  - path: patches/ingr.yaml
    target:
      kind: IngressRoute
      name: bazarr
  - path: patches/cert.yaml
    target:
      kind: Certificate
      name: bazarr
