apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  annotations:
    folder: media-server/prowlarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-1
