apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  annotations:
    folder: prowlarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: prowlarr-nfs
