apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:2.0.5@sha256:4f2a6d597845b2f3e19284b1d982b3e0b4bd7c22472c2979c956aa198b83f472
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - name: http
              containerPort: 9696
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
