apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: coredns
          image: coredns/coredns:1.13.2@sha256:94caebb89dcfb9d2c4be45bfda34410a3e1092458fbbbc0284365c9e4c9a7818
          args:
            - -conf
            - /etc/coredns/Corefile
          restartPolicy: Always
          volumeMounts:
            - name: prowlarr-coredns-config
              mountPath: /etc/coredns
        - name: gluetun
          image: qmcgaw/gluetun:v3.40.4@sha256:e10584de1f82d8999e5e6c3111901d9d56a2eed21151fb96af060f390bbdfba8
          restartPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - (ip rule del table 51820; ip -6 rule del table 51820) || true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: prowlarr-gluetun-config
              mountPath: /gluetun
        - name: ping
          image: busybox@sha256:d80cd694d3e9467884fcb94b8ca1e20437d8a501096cdf367a5a1918a34fc2fd
          command:
            - /bin/sh
            - -c
            - |
              while ! ping -c 1 cloudflare.com; do
                echo "Ping failed, retrying in 5 seconds..."
                sleep 5
              done
              echo "Ping successful, proceeding..."
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
          restartPolicy: Always
          ports:
            - name: http
              containerPort: 8191
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:2.3.0@sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          ports:
            - name: http
              containerPort: 9696
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: prowlarr-gluetun-config
          persistentVolumeClaim:
            claimName: prowlarr-gluetun-config
        - name: prowlarr-coredns-config
          configMap:
            name: prowlarr-coredns-config
