apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  annotations:
    folder: media-server/radarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-1
