apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  annotations:
    folder: radarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: radarr-nfs
