apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:5.19.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
          ports:
            - containerPort: 7878
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
