apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  annotations:
    folder: media-server/downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: nfs-hdd-1
