apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  annotations:
    folder: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: radarr-nfs
