apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: radarr
          port: http
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
  tls:
    secretName: radarr-tls
