apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  annotations:
    folder: movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: radarr-nfs
