apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: radarr-nfs-ssd
parameters:
  pathPattern: "media-server/${.PVC.annotations.folder}"
provisioner: nfs-ssd-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
