apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-videos
  annotations:
    folder: videos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: radarr-nfs
