apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  annotations:
    folder: sonarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sonarr-nfs-ssd
