apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.13
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
          ports:
            - name: http
              containerPort: 8989
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: shows
          persistentVolumeClaim:
            claimName: sonarr-shows
        - name: downloads
          persistentVolumeClaim:
            claimName: sonarr-downloads
