apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr-exportarr
spec:
  selector:
    matchLabels:
      app: sonarr
  endpoints:
    - port: http-metrics
      path: /metrics
