apiVersion: v1
kind: Service
metadata:
  name: sonarr-exportarr
  labels:
    app: sonarr
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9707
      targetPort: 9707
  selector:
    app: sonarr
