apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: sonarr
          port: http
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
    - kind: Rule
      services:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
          port: http
  tls:
    secretName: sonarr-tls
