apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  annotations:
    folder: qbittorrent/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: qbittorrent-nfs
