apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  annotations:
    folder: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: qbittorrent-nfs-hdd
