apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config
  annotations:
    folder: gluetun/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: qbittorrent-nfs
