apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config
  annotations:
    folder: media-server/gluetun/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-1
