apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: qbittorrent
          port: http
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
  tls:
    secretName: qbittorrent-tls
