apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-trackers
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trackers
              image: bash:5.3.3
              command:
                - bash
              env:
                - name: QBITTORRENT_HOST
                  value: http://qbittorrent.qbittorrent.svc.cluster.local
                - name: QBITTORRENT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent
                      key: qbittorrent-username
                - name: QBITTORRENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent
                      key: qbittorrent-password
          restartPolicy: OnFailure
