apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-trackers
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trackers
              image: bash:5.3.3@sha256:ae4668c2560999e65e89532cd2ad1b6688bb23298189f0bd229ef80fa4bd0831
              command:
                - bash
              args:
                - -c
              env:
                - name: QBITTORRENT_HOST
                  value: http://qbittorrent.qbittorrent.svc.cluster.local
                - name: QBITTORRENT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent
                      key: qbittorrent-username
                - name: QBITTORRENT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent
                      key: qbittorrent-password
          restartPolicy: OnFailure
