- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: VPN_SERVICE_PROVIDER
    value: protonvpn
- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: SERVER_COUNTRIES
    value: Iceland,Switzerland,Sweden
- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: VPN_TYPE
    value: wireguard
- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: WIREGUARD_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: qbittorrent-gluetun-protonvpn
        key: wireguard-private-key
- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: DOT
    value: "off"
