- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: VPN_PORT_FORWARDING_UP_COMMAND
    value: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" https://qbittorrent.home.albertv.dev/api/v2/app/setPreferences 2>&1'
