apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qbittorrent
resources:
  - resources/ns.yaml
  - resources/deployment.yaml
  - resources/nfs-storage-class.yaml
  - resources/config-pvc.yaml
  - resources/gluetun-config-pvc.yaml
  - resources/downloads-pvc.yaml
  - resources/svc.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
