apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  annotations:
    folder: media-server/jellyfin/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-1
