apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.10.6
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /data/shows
            - name: movies
              mountPath: /data/movies
          ports:
            - containerPort: 8096
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: shows
          persistentVolumeClaim:
            claimName: jellyfin-shows
        - name: movies
          persistentVolumeClaim:
            claimName: jellyfin-movies
