apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: jellyfin
          port: http
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
  tls:
    secretName: jellyfin-tls
