apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  annotations:
    folder: media-server/movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-hdd-1
