apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shows
  annotations:
    folder: shows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: jellyfin-nfs
