apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-videos
  annotations:
    folder: videos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: jellyfin-nfs
