apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - resources/ns.yaml
  - resources/deployment.yaml
  - resources/config-pvc.yaml
  - resources/shows-pvc.yaml
  - resources/movies-pvc.yaml
  - resources/svc.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
