apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  annotations:
    folder: bazarr/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: bazarr-nfs-ssd
