apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: linuxserver/bazarr:1.5.4@sha256:3785c9b813985821c9b56ee88c516d96b37dc21242c8f315f52e87c029735695
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          ports:
            - name: http
              containerPort: 6767
          livenessProbe:
            httpGet:
              path: /api/system/ping
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/system/ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /tv
            - name: movies
              mountPath: /movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: shows
          persistentVolumeClaim:
            claimName: bazarr-shows
        - name: movies
          persistentVolumeClaim:
            claimName: bazarr-movies
