apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-shows
  annotations:
    folder: media-server/shows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-hdd-1
