apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-shows
  annotations:
    folder: shows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: bazarr-nfs-hdd
