apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: qbittorrent
  - path: patches/ingr.yaml
    target:
      kind: IngressRoute
      name: qbittorrent
  - path: patches/cert.yaml
    target:
      kind: Certificate
      name: qbittorrent
