apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraparr
spec:
  selector:
    matchLabels:
      app: scraparr
  template:
    metadata:
      labels:
        app: scraparr
    spec:
      containers:
        - name: scraparr
          image: thegameprofi/scraparr:2.2.5@sha256:cfe07f005aa6e93221dd0bb540600aaa51ea1215968595806863f9df3dc3b26c
          ports:
            - name: http-metrics
              containerPort: 7100
          volumeMounts:
            - name: config
              mountPath: /scraparr/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: scraparr-config
