apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraparr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraparr
  template:
    metadata:
      labels:
        app: scraparr
    spec:
      containers:
        - name: scraparr
          image: thegameprofi/scraparr:2.2.4@sha256:4aa7e22f7a632082dbfe6e4be694068b08e5764b83c95339220ff2b33bf43be2
          ports:
            - name: http-metrics
              containerPort: 7100
          volumeMounts:
            - name: config
              mountPath: /scraparr/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: scraparr-config
