apiVersion: v1
kind: Service
metadata:
  name: scraparr
  labels:
    app: scraparr
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 7100
      targetPort: http-metrics
  selector:
    app: scraparr
