apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - resources/overlay-cm.yaml
  - resources/jellyfin.yaml
  - resources/sonarr.yaml
  - resources/radarr.yaml
  - resources/prowlarr.yaml
  - resources/qbittorrent.yaml
  - resources/bazarr.yaml
patches:
  - path: patches/application.yaml
    target:
      kind: Application
