apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  annotations:
    folder: jackett/config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: jackett-nfs
