apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jackett
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      services:
        - name: jackett
          port: 80
      middlewares:
        - name: traefik-error-pages
          namespace: traefik
  tls:
    secretName: jackett-tls
