apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: scraparr
resources:
  - resources/ns.yaml
  - resources/deployment.yaml
  - resources/svc.yaml
  - resources/svc-monitor.yaml
configMapGenerator:
  - name: scraparr-grafana-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Media Server
    files:
      - scraparr.json=assets/grafana-dashboard.json
