name: Test Build

on:
  pull_request:

jobs:
  kustomize-changed-overlays:
    name: Kustomize Changed Overlays
    runs-on: ubuntu-latest
    outputs:
      changed-overlays: ${{ steps.find-changed-kustomize-overlays.outputs.changed-overlays }}
    steps:
      - id: find-changed-kustomize-overlays
        name: Find Changed Kustomize Overlays
        uses: eviive/actions/find/kustomize/changed-overlays@main

  build-kustomize-overlay:
    name: Build Kustomize Overlay
    needs: kustomize-changed-overlays
    if: needs.kustomize-changed-overlays.outputs.changed-overlays != '[]'
    strategy:
      fail-fast: false
      matrix:
        overlay: ${{ fromJSON(needs.kustomize-changed-overlays.outputs.changed-overlays) }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Kustomize overlay
        uses: eviive/actions/build/kustomize@main
        with:
          working-directory: ${{ matrix.overlay }}
